version: "3.5"

services:
  pgserver:
    image: postgis/postgis:14-master
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ../tmp/db:/var/lib/postgresql/data
      - ./create-test-db.sh:/docker-entrypoint-initdb.d/create-test-db.sh
      - ../data:/geodata
    env_file: ../.env
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "0.0.0.0:5433:80"
    env_file: ../.env
    volumes:
      - ./pgadmin4-servers.json:/pgadmin4/servers.json